import { motion, AnimatePresence } from 'framer-motion'
import { Sparkles, ArrowRight } from 'lucide-react'
import Header from './components/Header'
import Footer from './components/Footer'
import FlowDiagram from './components/FlowDiagram'
import SimulationBar from './components/SimulationBar'
import StepPanel from './components/StepPanel'
import ReactMarkdown from 'react-markdown'
import { useRagStore, STEP_IDS, STEP_META } from './lib/store'

export default function App() {
  const steps = useRagStore((s) => s.steps)
  const isSimulating = useRagStore((s) => s.isSimulating)
  const runSimulation = useRagStore((s) => s.runSimulation)
  const resetPipeline = useRagStore((s) => s.resetPipeline)
  const openStep = useRagStore((s) => s.openStep)

  const finalOutput = steps.generate.output
  const anyComplete = STEP_IDS.some((id) => steps[id].status === 'complete')

  return (
    <div className="min-h-screen flex flex-col">
      <Header />

      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 py-8 sm:py-12">
        <SimulationBar
          steps={steps}
          isSimulating={isSimulating}
          onStart={runSimulation}
          onReset={resetPipeline}
        />

        <FlowDiagram steps={steps} onStepClick={openStep} />

        <AnimatePresence>
          {finalOutput && (
            <motion.section
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="mt-8 rounded-3xl border border-signal/40 bg-gradient-to-br from-signal/10 via-ink-800 to-vector/10 p-6 sm:p-8"
            >
              <div className="flex items-center gap-2 mb-3">
                <Sparkles size={16} className="text-signal" />
                <p className="text-xs uppercase tracking-wider text-signal font-mono">Final output</p>
              </div>
              <div className="font-display text-lg sm:text-xl text-mist-100 leading-relaxed prose prose-invert prose-lg sm:prose-xl max-w-none prose-p:my-2 prose-strong:text-signal prose-headings:text-mist-100 prose-li:my-0.5 prose-headings:font-display">
                <ReactMarkdown>{finalOutput.answer}</ReactMarkdown>
              </div>
              <p className="text-xs text-mist-500 mt-4 font-mono">
                generated by {finalOutput.model_id} &middot; {finalOutput.latency_ms}ms &middot; {finalOutput.retrieved_chunks.length} chunks used
              </p>
            </motion.section>
          )}
        </AnimatePresence>

        {anyComplete && (
          <section className="mt-8">
            <p className="text-xs uppercase tracking-wider text-mist-500 font-mono mb-3">Step outputs</p>
            <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
              {STEP_IDS.map((id) => {
                const s = steps[id]
                return (
                  <button
                    key={id}
                    onClick={() => openStep(id)}
                    disabled={s.status !== 'complete' && s.status !== 'error'}
                    className="text-left bg-ink-800/60 border border-ink-600 rounded-xl p-3.5 hover:border-signal/60 transition-colors disabled:opacity-40 disabled:cursor-not-allowed group"
                  >
                    <div className="flex items-center justify-between mb-1">
                      <p className="text-xs font-medium text-mist-200">{STEP_META[id].title}</p>
                      <ArrowRight size={12} className="text-mist-500 group-hover:text-signal transition-colors" />
                    </div>
                    <p className="text-[10px] font-mono text-mist-500 capitalize">{s.status}</p>
                  </button>
                )
              })}
            </div>
          </section>
        )}

        <section className="mt-12 grid sm:grid-cols-3 gap-4">
          {[
            { title: 'Tweak any step', desc: 'Open a step to adjust its inputs — chunk size, query, model — and see how the output changes.' },
            { title: 'Run from anywhere', desc: 'Restart the pipeline from a specific step while keeping the rest of your configuration.' },
            { title: 'See the vectors', desc: 'Embeddings and semantic search are visualized on a live 2D projection, not just numbers.' },
          ].map((c) => (
            <div key={c.title} className="bg-ink-800/40 border border-ink-600/60 rounded-2xl p-4">
              <p className="text-sm font-display font-semibold text-mist-100">{c.title}</p>
              <p className="text-xs text-mist-500 mt-1.5 leading-relaxed">{c.desc}</p>
            </div>
          ))}
        </section>
      </main>

      <StepPanel />
      <Footer />
    </div>
  )
}
